---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.cache # includes bowers cache
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default
  - COVERAGE=true

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: COVERAGE=true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt greenkeeper-lockfile@1
  - bower --version
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - bower install

before_script: greenkeeper-lockfile-update

script:
  - npm run-script run-travis

after_script:
  - greenkeeper-lockfile-upload
